/**
 * Worker bindings, hand-written rather than generated by `wrangler types`.
 *
 * The binding surface is small and changes rarely, so committing this file
 * keeps CI free of a codegen step and keeps the generated
 * worker-configuration.d.ts out of the repo. Keep in sync with wrangler.jsonc.
 */
export type Bindings = {
  DB: D1Database;
  MEDIA: R2Bucket;
  ASSETS: Fetcher;
  ENVIRONMENT?: string;
  /** Extra entropy for session token hashing. Set as a secret per environment. */
  SESSION_PEPPER?: string;
};
