/**
 * Worker bindings, hand-written rather than generated by `wrangler types`.
 *
 * The binding surface is small and changes rarely, so committing this file
 * keeps CI free of a codegen step and keeps the generated
 * worker-configuration.d.ts out of the repo. Keep in sync with wrangler.jsonc.
 */
export type Bindings = {
  DB: D1Database;
  MEDIA: R2Bucket;
  ASSETS: Fetcher;
  EMAIL: SendEmail;
  ENVIRONMENT?: string;
  /** Extra entropy for session token hashing. Set as a secret per environment. */
  SESSION_PEPPER?: string;
  /**
   * Shared code required by POST /api/auth/coach-signup. Production is at a
   * guessable URL and self-serve onboarding (COG-018) does not exist yet, so
   * without this anyone could mint a team. Unset means signup is closed.
   */
  ALPHA_SIGNUP_CODE?: string;
  /** Absolute base URL used to build invite links in outgoing mail. */
  APP_BASE_URL?: string;
};
